### ISSUE TITLE
How to pass `max_token_length` to `load_model` ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [hyperonym/basaran#116]
I want the model to keep outputing text for the `max_token_length` i specify.

**Comment by peakji** [comment]
Hi @MohamedAliRashad !

If you want to limit the maximum allowed number of output tokens, use the `COMPLETION_MAX_TOKENS` environment variable (default is **4096**).

If you want the model to always output text up to a certain length, use the `min_tokens` request parameter.
