### ISSUE TITLE
How can I use this with a project using OpenAI's nodejs library?

### ISSUE THREAD

**Issue by MarkSchmidty** [hyperonym/basaran#120]
OpenAI's official node.js library does not support changing the API URL endpoint.

Is there a workaround or other libraries I could be using?

**Comment by peakji** [comment]
Hi @MarkSchmidty , it seems the nodejs library provides a [`basePath` option](https://github.com/openai/openai-node/blob/master/configuration.ts#L70] in `Configuration`.

**Comment by MarkSchmidty** [comment]
I didn't realize that. But I think this resolves my issue/question. Thank you!
