### ISSUE TITLE
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by josephrocca** [hyperonym/basaran#139]
Running this command:
```
docker run -p 80:80 -e MODEL=decapoda-research/llama-7b-hf hyperonym/basaran:0.15.3
```
Gives:
```
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
```

It worked fine with the `cerebras/Cerebras-GPT-1.3B` and `bigscience/bloom-560m` models.

(Thanks for your work on this project! Currently integrating it with [OpenCharacters](https://github.com/josephrocca/OpenCharacters))

**Comment by peakji** [comment]
Hi @josephrocca, `decapoda-research/llama-7b-hf` hasn't been updated to use the new class name (`LLaMATokenizer` -> `LlamaTokenizer`). You could just pick another LLaMA model from Hugging Face Hub.

Related: https://github.com/hyperonym/basaran/issues/57#issuecomment-1509036822
