### ISSUE TITLE
Possible to run on M-series chips/MPS?

### ISSUE THREAD

**Issue by fakerybakery** [hyperonym/basaran#173]
Hello,
Thank you for making this great repository! Is it possible to run this on M1/M2 chips using MPS? I've tried setting `self.device` to `mps`, however I get this:
```
RuntimeError: Placeholder storage has not been allocated on MPS device!
```
Is there any way to run this using MPS optimization?
Thank you!

**Comment by peakji** [comment]
I haven't used MPS before, will investigate it.

**Comment by fardeon** [comment]
After some attempts, I found that setting `device="mps"` alone is not enough, and we also need an additional `model.to("mps")` to run.

What's even stranger is that the inference speed actually decreases significantly when using MPS compared to using CPU (Macbook Pro M1).

**Comment by fakerybakery** [comment]
OK, thank you. I will try that out.
