### ISSUE TITLE
concurrent request supported?

### ISSUE THREAD

**Issue by hudengjunai** [hyperonym/basaran#205]
Does this server support concurent request ?
Is is thread-safe for concurent request?

**Comment by peakji** [comment]
> Does this server support concurent request ?

Yes, the server supports up to `SERVER_THREADS` (default = 32) concurrent requests. It is recommended to set this environment variable to a number that's larger than your number of CPU threads, especially when you're using GPUs.

> Is is thread-safe for concurent request?

In general, all the objects in Basaran and PyTorch are thread safe to read. But we cannot guarantee thread-safe for other native components in dependencies.
