### ISSUE TITLE
Beam search

### ISSUE THREAD

**Issue by lcw99** [hyperonym/basaran#97]
I am using this package, which shows much better performance than MS DeepSpeed-MII, which has a similar function. Do you have plans to implement beam search as well?

**Comment by peakji** [comment]
Currently we do not have plans to implement beam search. On one hand, it would incur greater performance overhead, and on the other hand, if you want to generate natural text, [beam search may not be the best choice](https://arxiv.org/abs/1904.09751).

<img width="456" src="https://user-images.githubusercontent.com/219051/227828625-3f375941-eae7-4ba8-99d6-90dcfdff7c0c.png">

**Comment by lcw99** [comment]
Thanks for your answer. I really expecting Frequency and presence penalties functionality. Currently, I have some repetation problem on my model.
